# This is a TOML document. Boom.

title = "TOML Example"

[server]
port = 3000

[databases]
  [databases.default]
  Driver   = "postgres"
  Name     = "cloud11"
  User     = "mi"
  Password = "dummy"
  Host     = "localhost"
  Port     = 5432

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[storages]

  # You can indent as you please. Tabs or spaces. TOML don't care.
  [storages.home]
  root = "/Users/mi/tmp"
  baseUrl = "/home"
  serveUrl = "/serve/home"
  albumPath = "/alben"
  group = 20
  

  [storages.public]
  root = "/Users/mi/Downloads"
  baseUrl = "/public"
  serveUrl = "/serve"
  albumPath = "/publicalben"
  mode = 360
  

[accounts]

    [accounts.matthias]
