# This is a TOML document. Boom.

title = "TOML Example"

[server]
port = 3000

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002 ]
connection_max = 5000
enabled = true

[storages]

  # You can indent as you please. Tabs or spaces. TOML don't care.
  [storages.home]
  root = "/Users/mi/tmp"
  path = "/home"
  group = 20

  [storages.public]
  root = "/Users/mi/Downloads"
  path = "/public/"


